/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.*;
import POJO.POJO_Combomonan;
import java.awt.Image;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class frm_HocSinh_KPA extends javax.swing.JFrame {

    /**
     * Creates new form frm_ThietLap_KPA
     */
    Vector tblDataman = new Vector();
    Vector tblTitleman = new Vector();
    DefaultTableModel tblModelman;
    static ArrayList<POJO_Combomonan> dscbman;

    Vector tblDatachay = new Vector();
    Vector tblTitlechay = new Vector();
    DefaultTableModel tblModelchay;
    static ArrayList<POJO_Combomonan> dscbchay;

    static String QR = "";

    public frm_HocSinh_KPA() {
        initComponents();
        jTable_combomonanchay.setDefaultEditor(Object.class, null);
        jTable_combomonanman.setDefaultEditor(Object.class, null);

        jTable_combomonanchay.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable_combomonanman.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        tblModelman = new DefaultTableModel();
        tblTitleman.add("Mã Cb");
        tblTitleman.add("Món 1");
        tblTitleman.add("Món 2");
        tblTitleman.add("Món 3");
        tblTitleman.add("Món 4");
        tblTitleman.add("Loại");
        tblTitleman.add("Thứ");
        tblTitleman.add("Giá tiền");
        tblTitleman.add("QRCode");
        showDuLieu_ComBoMonAnHienThi_KPMan(dscbman);

        tblModelchay = new DefaultTableModel();
        tblTitlechay.add("Mã Cb");
        tblTitlechay.add("Món 1");
        tblTitlechay.add("Món 2");
        tblTitlechay.add("Món 3");
        tblTitlechay.add("Món 4");
        tblTitlechay.add("Loại");
        tblTitlechay.add("Thứ");
        tblTitlechay.add("Giá tiền");
        tblTitlechay.add("QRCode");
        showDuLieu_ComBoMonAnHienThi_KPChay(dscbchay);

    }

    // load ds khẩn phần mặn
    public void showDuLieu_ComBoMonAnHienThi_KPMan(ArrayList<POJO_Combomonan> dscbhtman) {
        dscbhtman = DAO_KhauPhanAn.getDSComBoMonAnHienThi_Man();

        tblDataman.removeAllElements();
        for (POJO_Combomonan b : dscbhtman) {
            Vector v = new Vector();
            v.add(b.getMaComBoMon());
            v.add(b.getTenMon1());
            v.add(b.getTenMon2());
            v.add(b.getTenMon3());
            v.add(b.getTenMon4());
            v.add(b.getLoaiComBoMon());
            v.add(b.getThuTrongTuan());
            v.add(b.getGiaTien());
            v.add(b.getQRCode());
            tblDataman.add(v);
        }
        jTable_combomonanman.setModel(new DefaultTableModel(tblDataman, tblTitleman));
    }

    // load ds khẩn phần chay
    public void showDuLieu_ComBoMonAnHienThi_KPChay(ArrayList<POJO_Combomonan> dscbhtchay) {
        dscbhtchay = DAO_KhauPhanAn.getDSComBoMonAnHienThi_Chay();

        tblDatachay.removeAllElements();
        for (POJO_Combomonan b : dscbhtchay) {
            Vector v = new Vector();
            v.add(b.getMaComBoMon());
            v.add(b.getTenMon1());
            v.add(b.getTenMon2());
            v.add(b.getTenMon3());
            v.add(b.getTenMon4());
            v.add(b.getLoaiComBoMon());
            v.add(b.getThuTrongTuan());
            v.add(b.getGiaTien());
            v.add(b.getQRCode());
            tblDatachay.add(v);
        }
        jTable_combomonanchay.setModel(new DefaultTableModel(tblDatachay, tblTitlechay));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_combomonanman = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_combomonanchay = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_loai = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_thu = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_gia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_mon1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_mon2 = new javax.swing.JTextField();
        txt_mon3 = new javax.swing.JTextField();
        txt_mon4 = new javax.swing.JTextField();
        btn_dangki = new javax.swing.JButton();
        btn_xemthongtin = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel_qr = new javax.swing.JLabel();
        btn_quaylai1 = new javax.swing.JButton();

        jButton6.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ĐĂNG KÍ KHẨU PHẦN ĂN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 51, 51))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Các khẩu phần trong tuần", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18), new java.awt.Color(255, 51, 51))); // NOI18N

        jTable_combomonanman.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable_combomonanman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_combomonanman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_combomonanmanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_combomonanman);

        jTable_combomonanchay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable_combomonanchay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable_combomonanchay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_combomonanchayMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_combomonanchay);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin combo món", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(255, 0, 51))); // NOI18N

        jLabel9.setText("Mã Combo:");

        txt_ma.setEnabled(false);
        txt_ma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maActionPerformed(evt);
            }
        });

        jLabel10.setText("Loại combo:");

        txt_loai.setEnabled(false);

        jLabel11.setText("Thứ:");

        txt_thu.setEnabled(false);

        jLabel12.setText("Giá tiền:");

        txt_gia.setEnabled(false);

        jLabel13.setText("Món 1:");

        txt_mon1.setEnabled(false);

        jLabel14.setText("Món 2:");

        jLabel15.setText("Món 3:");

        jLabel16.setText("Món 4:");

        txt_mon2.setEnabled(false);

        txt_mon3.setEnabled(false);

        txt_mon4.setEnabled(false);

        btn_dangki.setBackground(new java.awt.Color(204, 204, 204));
        btn_dangki.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_dangki.setText("Đăng kí");
        btn_dangki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangkiActionPerformed(evt);
            }
        });

        btn_xemthongtin.setBackground(new java.awt.Color(204, 204, 204));
        btn_xemthongtin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_xemthongtin.setText("Xem thông tin đăng kí");
        btn_xemthongtin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xemthongtinActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QR Code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(255, 51, 51))); // NOI18N

        jLabel_qr.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel_qr, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_qr, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_dangki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_xemthongtin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_mon4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_mon3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_mon2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_mon1))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ma))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_thu, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_gia, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_loai)))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txt_loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_thu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txt_gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_mon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txt_mon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_mon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txt_mon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btn_dangki)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_xemthongtin)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_quaylai1.setBackground(new java.awt.Color(204, 204, 204));
        btn_quaylai1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_quaylai1.setForeground(new java.awt.Color(255, 51, 0));
        btn_quaylai1.setText("QUAY LẠI");
        btn_quaylai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quaylai1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_quaylai1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_quaylai1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //lấy đường dẫn hình ảnh
    public String duongDanHinhAnh(String tenHinh) {
        // Chuyển đổi đường dẫn tương đối thành đối tượng File
        String tenThuMucHinhAnh = "src\\IMG_QRCode";
        File imageDirectory = new File(tenThuMucHinhAnh);

        // Lấy đường dẫn tuyệt đối của thư mục hình ảnh
        String thuMucHinhAnh_ddTuyetDoi = imageDirectory.getAbsolutePath();

        // Tạo đường dẫn tuyệt đối đến hình ảnh
        String imgPath = thuMucHinhAnh_ddTuyetDoi + File.separator + tenHinh;

        return imgPath;
    }

    private void btn_dangkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangkiActionPerformed

        String macb = txt_ma.getText();
        if (macb.equals("") == true) {
            JOptionPane.showMessageDialog(rootPane, "Chưa chọn khẩu phần!");
        } else {  
            int thu = Integer.parseInt(txt_thu.getText());
            String userName = DAO_KhauPhanAn.kiemTraUser();
            String ngayDK = layNgayHeThong();
            float gia = Float.parseFloat(txt_gia.getText());

            String str = QR;

            int chon = JOptionPane.showConfirmDialog(null, "Bạn đã chắn chắn!",
                    "Xác nhận", JOptionPane.YES_NO_OPTION);

            int tam = DAO_KhauPhanAn.dangKi_KPA(userName, macb, ngayDK, thu, gia, QR);
            if (tam == 1) {
                JOptionPane.showMessageDialog(rootPane, "Đăng kí thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Khẩu phần thứ " + thu + " đã được đăng kí!");
            }
        }

    }//GEN-LAST:event_btn_dangkiActionPerformed

    private void btn_xemthongtinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xemthongtinActionPerformed
        // TODO add your handling code here:
        frm_ThongTinDangKy fr = new frm_ThongTinDangKy();
        fr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_xemthongtinActionPerformed

    private void jTable_combomonanmanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_combomonanmanMouseClicked
        // TODO add your handling code here:      
        jTable_combomonanchay.clearSelection();

        int row = jTable_combomonanman.getSelectedRow();

        String macb = jTable_combomonanman.getValueAt(row, 0).toString();
        String mon1 = jTable_combomonanman.getValueAt(row, 1).toString();
        String mon2 = jTable_combomonanman.getValueAt(row, 2).toString();
        String mon3 = jTable_combomonanman.getValueAt(row, 3).toString();
        String mon4 = jTable_combomonanman.getValueAt(row, 4).toString();
        String loai = jTable_combomonanman.getValueAt(row, 5).toString();
        String thu = jTable_combomonanman.getValueAt(row, 6).toString();
        String gia = jTable_combomonanman.getValueAt(row, 7).toString();
        QR = jTable_combomonanman.getValueAt(row, 8).toString();

        txt_ma.setText(macb);
        txt_loai.setText(loai);
        txt_gia.setText(gia);
        txt_thu.setText(thu);
        txt_mon1.setText(mon1);
        txt_mon2.setText(mon2);
        txt_mon3.setText(mon3);
        txt_mon4.setText(mon4);

        String imagePath = duongDanHinhAnh(QR);

        // Tạo ImageIcon từ ảnh
        ImageIcon originalIcon = new ImageIcon(imagePath);

        // Lấy kích thước của JLabel
        int labelWidth = 90;
        int labelHeight = 90;

        // Chuyển đổi ImageIcon thành Image để điều chỉnh kích thước
        Image originalImage = originalIcon.getImage();

        // Điều chỉnh kích thước của ảnh
        Image scaledImage = originalImage.getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);

        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        // Tạo JLabel để hiển thị ảnh
        jLabel_qr.setIcon(scaledIcon);

    }//GEN-LAST:event_jTable_combomonanmanMouseClicked

    private void jTable_combomonanchayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_combomonanchayMouseClicked
        // TODO add your handling code here:

        jTable_combomonanman.clearSelection();

        int row = jTable_combomonanchay.getSelectedRow();

        String macb = jTable_combomonanchay.getValueAt(row, 0).toString();
        String mon1 = jTable_combomonanchay.getValueAt(row, 1).toString();
        String mon2 = jTable_combomonanchay.getValueAt(row, 2).toString();
        String mon3 = jTable_combomonanchay.getValueAt(row, 3).toString();
        String mon4 = jTable_combomonanchay.getValueAt(row, 4).toString();
        String loai = jTable_combomonanchay.getValueAt(row, 5).toString();
        String thu = jTable_combomonanchay.getValueAt(row, 6).toString();
        String gia = jTable_combomonanchay.getValueAt(row, 7).toString();
        QR = jTable_combomonanchay.getValueAt(row, 8).toString();

        txt_ma.setText(macb);
        txt_loai.setText(loai);
        txt_gia.setText(gia);
        txt_thu.setText(thu);
        txt_mon1.setText(mon1);
        txt_mon2.setText(mon2);
        txt_mon3.setText(mon3);
        txt_mon4.setText(mon4);

        String imagePath = duongDanHinhAnh(QR);

        // Tạo ImageIcon từ ảnh
        ImageIcon originalIcon = new ImageIcon(imagePath);

        // Lấy kích thước của JLabel
        int labelWidth = 90;
        int labelHeight = 90;

        // Chuyển đổi ImageIcon thành Image để điều chỉnh kích thước
        Image originalImage = originalIcon.getImage();

        // Điều chỉnh kích thước của ảnh
        Image scaledImage = originalImage.getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);

        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        // Tạo JLabel để hiển thị ảnh
        jLabel_qr.setIcon(scaledIcon);
    }//GEN-LAST:event_jTable_combomonanchayMouseClicked

    private void txt_maActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maActionPerformed

    private void btn_quaylai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quaylai1ActionPerformed
        // TODO add your handling code here: 
        Managanent_GUI fr = new Managanent_GUI();
        fr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_quaylai1ActionPerformed

    public String layNgayHeThong() {
        // Lấy ngày hiện tại từ hệ thống
        Date currentDate = new Date();
        // Xác định định dạng ngày tháng mặc định của hệ thống
        DateFormat systemDateFormat = DateFormat.getDateInstance();
        // Định dạng ngày thành chuỗi với định dạng mặc định của hệ thống
        String formattedDate = systemDateFormat.format(currentDate);
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String ngayHeThong = dateFormat.format(currentDate);
        return ngayHeThong;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_HocSinh_KPA.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_HocSinh_KPA.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_HocSinh_KPA.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_HocSinh_KPA.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_HocSinh_KPA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangki;
    private javax.swing.JButton btn_quaylai1;
    private javax.swing.JButton btn_xemthongtin;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_qr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_combomonanchay;
    private javax.swing.JTable jTable_combomonanman;
    private javax.swing.JTextField txt_gia;
    private javax.swing.JTextField txt_loai;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_mon1;
    private javax.swing.JTextField txt_mon2;
    private javax.swing.JTextField txt_mon3;
    private javax.swing.JTextField txt_mon4;
    private javax.swing.JTextField txt_thu;
    // End of variables declaration//GEN-END:variables
}
