/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.*;
import POJO.POJO_Combomonan;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.Window;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.net.URI;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;

/**
 *
 * @author ACER
 */
public class frm_QuanLi_KPA extends javax.swing.JFrame {

    /**
     * Creates new form frm_ThietLap_KPA
     */
    Vector tblData = new Vector();
    Vector tblTitle = new Vector();
    DefaultTableModel tblModel;

    static ArrayList<POJO_Combomonan> dscbc;
    static ArrayList<POJO_Combomonan> dscbht;

    static int thieilap = 0;
    static int suadoi = 0;

    static int kpCu = 0;
    static int kpMoi = 0;
    static File img = null;
    static String fileName = "";

    public frm_QuanLi_KPA() {
        initComponents();
        //cho chon trên lưới, không cho chỉnh sửa
        jTable_combomonan.setDefaultEditor(Object.class, null);
    }

    //lấy đường dẫn hình ảnh
    public String duongDanHinhAnh(String tenHinh) {
        // Chuyển đổi đường dẫn tương đối thành đối tượng File
        String tenThuMucHinhAnh = "src\\IMG_QRCode";
        File imageDirectory = new File(tenThuMucHinhAnh);

        // Lấy đường dẫn tuyệt đối của thư mục hình ảnh
        String thuMucHinhAnh_ddTuyetDoi = imageDirectory.getAbsolutePath();

        // Tạo đường dẫn tuyệt đối đến hình ảnh
        String imgPath = thuMucHinhAnh_ddTuyetDoi + File.separator + tenHinh;

        return imgPath;
    }

    // load ds 
    public void showDuLieu_ComBoMonAnCu(ArrayList<POJO_Combomonan> dscbc) {
        dscbc = DAO_KhauPhanAn.getDSComBoMonAN();

        tblData.removeAllElements();
        for (POJO_Combomonan b : dscbc) {
            Vector v = new Vector();
            v.add(b.getMaComBoMon());
            v.add(b.getTenMon1());
            v.add(b.getTenMon2());
            v.add(b.getTenMon3());
            v.add(b.getTenMon4());
            v.add(b.getLoaiComBoMon());
            v.add(b.getThuTrongTuan());
            v.add(b.getGiaTien());
            v.add(b.getQRCode());
            tblData.add(v);
        }
        jTable_combomonan.setModel(new DefaultTableModel(tblData, tblTitle));
    }

    // load ds 
    public void showDuLieu_ComBoMonAnHienThi(ArrayList<POJO_Combomonan> dscbht) {
        dscbht = DAO_KhauPhanAn.getDSComBoMonAnHienThi();

        tblData.removeAllElements();
        for (POJO_Combomonan b : dscbht) {
            Vector v = new Vector();
            v.add(b.getMaComBoMon());
            v.add(b.getTenMon1());
            v.add(b.getTenMon2());
            v.add(b.getTenMon3());
            v.add(b.getTenMon4());
            v.add(b.getLoaiComBoMon());
            v.add(b.getThuTrongTuan());
            v.add(b.getGiaTien());
            v.add(b.getQRCode());
            tblData.add(v);
        }
        jTable_combomonan.setModel(new DefaultTableModel(tblData, tblTitle));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_combomonan = new javax.swing.JTable();
        btn_kpcu = new javax.swing.JButton();
        btn_khmoi = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_ma = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_loai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_thu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_gia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_mon1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_mon2 = new javax.swing.JTextField();
        txt_mon3 = new javax.swing.JTextField();
        txt_mon4 = new javax.swing.JTextField();
        btn_huy = new javax.swing.JButton();
        btn_them = new javax.swing.JButton();
        btn_taoqr = new javax.swing.JButton();
        btn_themqr = new javax.swing.JButton();
        btn_xacnhan = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel_qr = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_thietlap = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa_all = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_themvaokhauphanDK = new javax.swing.JButton();
        btn_quaylai = new javax.swing.JButton();

        jButton6.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QUẢN LÍ KHẨU PHẦN ĂN HỌC SINH", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(255, 51, 51))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Các khẩu phần trong tuần", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18), new java.awt.Color(255, 51, 51))); // NOI18N

        jTable_combomonan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable_combomonan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_combomonanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable_combomonanMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_combomonan);

        btn_kpcu.setText("KP đã thiết lập");
        btn_kpcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kpcuActionPerformed(evt);
            }
        });

        btn_khmoi.setText("KP mới");
        btn_khmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_khmoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_kpcu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_khmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_kpcu)
                    .addComponent(btn_khmoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin combo món", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(255, 0, 51))); // NOI18N

        jLabel1.setText("Mã Combo:");

        txt_ma.setEnabled(false);

        jLabel2.setText("Loại combo:");

        txt_loai.setEnabled(false);

        jLabel3.setText("Thứ:");

        txt_thu.setEnabled(false);

        jLabel4.setText("Giá tiền:");

        txt_gia.setEnabled(false);

        jLabel5.setText("Món 1:");

        txt_mon1.setEnabled(false);

        jLabel6.setText("Món 2:");

        jLabel7.setText("Món 3:");

        jLabel8.setText("Món 4:");

        txt_mon2.setEnabled(false);

        txt_mon3.setEnabled(false);

        txt_mon4.setEnabled(false);

        btn_huy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_huy.setText("Hủy");
        btn_huy.setEnabled(false);
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        btn_them.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_them.setText("Thêm");
        btn_them.setEnabled(false);
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_taoqr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_taoqr.setText("Tạo QR");
        btn_taoqr.setEnabled(false);
        btn_taoqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taoqrActionPerformed(evt);
            }
        });

        btn_themqr.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_themqr.setText("Thêm QR");
        btn_themqr.setEnabled(false);
        btn_themqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themqrActionPerformed(evt);
            }
        });

        btn_xacnhan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_xacnhan.setText("Xác nhận");
        btn_xacnhan.setEnabled(false);
        btn_xacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xacnhanActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QR Code", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 12), new java.awt.Color(255, 51, 51))); // NOI18N

        jLabel_qr.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel_qr, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_qr, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn_xacnhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_mon4)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_mon3))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_mon2))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_mon1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_thu)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_gia))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txt_loai, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btn_themqr, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                        .addComponent(btn_taoqr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_ma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txt_loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_taoqr))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_thu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txt_gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_themqr))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_mon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txt_mon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_mon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_mon4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_xacnhan)
                    .addComponent(btn_them)
                    .addComponent(btn_huy))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thao tác", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14), new java.awt.Color(255, 51, 51))); // NOI18N

        btn_thietlap.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_thietlap.setText("Thiết lập khẩu phần ăn");
        btn_thietlap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thietlapActionPerformed(evt);
            }
        });

        btn_sua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_sua.setText("Sửa khẩu phần ăn");
        btn_sua.setEnabled(false);
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_xoa_all.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_xoa_all.setText("Xóa tất cả khẩu phẩn");
        btn_xoa_all.setEnabled(false);
        btn_xoa_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoa_allActionPerformed(evt);
            }
        });

        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_xoa.setText("Xóa khẩu phẩn");
        btn_xoa.setDoubleBuffered(true);
        btn_xoa.setEnabled(false);
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_themvaokhauphanDK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_themvaokhauphanDK.setText("Thêm vào ds đăng kí");
        btn_themvaokhauphanDK.setEnabled(false);
        btn_themvaokhauphanDK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themvaokhauphanDKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_thietlap, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_xoa_all, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_themvaokhauphanDK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_thietlap, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btn_xoa_all, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btn_themvaokhauphanDK, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_quaylai.setBackground(new java.awt.Color(204, 204, 204));
        btn_quaylai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_quaylai.setForeground(new java.awt.Color(255, 51, 0));
        btn_quaylai.setText("QUAY LẠI");
        btn_quaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quaylaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btn_quaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_quaylai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean ktThongTinNhapVao() {
        String mon1 = txt_mon1.getText();
        String mon2 = txt_mon2.getText();
        String mon3 = txt_mon3.getText();
        String mon4 = txt_mon4.getText();
        String loai = txt_loai.getText();
        String gia = txt_loai.getText();
        String thu = txt_thu.getText();

        if (mon1.equals("") || mon2.equals("") || mon3.equals("") || mon4.equals("")
                || loai.equals("") || gia.equals("") || thu.equals("")) {
            return false;
        }
        return true;
    }
    private void btn_xoa_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoa_allActionPerformed
        // TODO add your handling code here:
        btn_them.setEnabled(false);

        int chon = JOptionPane.showConfirmDialog(null, "Xóa danh sách khẩu phẩn ăn !",
                "Xác nhận", JOptionPane.YES_NO_OPTION);

        if (kpCu == 1) {
            if (chon == JOptionPane.YES_OPTION) {
                int tam1 = DAO_KhauPhanAn.xoaDuLieu_dangki();
                int tam = DAO_KhauPhanAn.xoaDuLieu_ComBoMonAn();
                //DAO_KhauPhanAn.xoaBienTuDongTangMaComnbo();
                if (tam == 1 && tam1 == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Đã xóa dữ liệu khẩu phần cũ...");
                    showDuLieu_ComBoMonAnCu(dscbc);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Xóa dữ liệu khẩu phần cũ thất bại...");
                }
            }
        }

        if (kpMoi == 1) {
            if (chon == JOptionPane.YES_OPTION) {
                int tam = DAO_KhauPhanAn.xoaDuLieu_ComBoMonAnHienThi();
                if (tam == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Đã xóa danh sách khẩu phần đăng kí ...");
                    showDuLieu_ComBoMonAnHienThi(dscbht);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Xóa thất bại...");
                }
            }
        }

    }//GEN-LAST:event_btn_xoa_allActionPerformed

    private void btn_thietlapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thietlapActionPerformed
        // TODO add your handling code here:
        suadoi = 0;
        thieilap = 1;
        img = null;

        btn_them.setEnabled(false);

        txt_ma.setText("");
        txt_mon1.setText("");
        txt_mon1.setText("");
        txt_mon2.setText("");
        txt_mon3.setText("");
        txt_mon4.setText("");
        txt_loai.setText("");
        txt_thu.setText("");
        txt_gia.setText("");

        txt_mon1.setEnabled(true);
        txt_mon2.setEnabled(true);
        txt_mon3.setEnabled(true);
        txt_mon4.setEnabled(true);
        txt_loai.setEnabled(true);
        txt_thu.setEnabled(true);
        txt_gia.setEnabled(true);

        jLabel_qr.setIcon(null);

        btn_xacnhan.setEnabled(true);
        btn_taoqr.setEnabled(true);
        btn_huy.setEnabled(true);
        btn_themqr.setEnabled(true);
    }//GEN-LAST:event_btn_thietlapActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        suadoi = 1;
        thieilap = 0;

        btn_them.setEnabled(false);

        txt_mon1.setEnabled(true);
        txt_mon2.setEnabled(true);
        txt_mon3.setEnabled(true);
        txt_mon4.setEnabled(true);
        txt_loai.setEnabled(true);
        txt_thu.setEnabled(true);
        txt_gia.setEnabled(true);

        btn_xacnhan.setEnabled(true);
        btn_huy.setEnabled(true);
        btn_taoqr.setEnabled(true);
        btn_themqr.setEnabled(true);
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_xacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xacnhanActionPerformed
        // TODO add your handling code here:

        if (ktThongTinNhapVao() == false) {
            JOptionPane.showMessageDialog(rootPane, "Chưa nhập đủ thông tin ...");
            return;
        }

        int chon = JOptionPane.showConfirmDialog(null, "Bạn đã chắn chắn!",
                "Xác nhận", JOptionPane.YES_NO_OPTION);

        //copy hình ảnh vào thư muc 
        if (img != null) {
            // Đường dẫn đến thư mục img
            String tenThuMucHinhAnh = "src\\IMG_QRCode";
            File imageDirectory = new File(tenThuMucHinhAnh);

            // Lấy đường dẫn tuyệt đối của thư mục hình ảnh
            String imgDirectoryPath = imageDirectory.getAbsolutePath();

            // Thực hiện sao chép tệp vào thư mục img
            try {
                Path destinationPath = new File(imgDirectoryPath, img.getName()).toPath();
                Files.copy(img.toPath(), destinationPath, StandardCopyOption.REPLACE_EXISTING);
            } catch (IOException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this,
                        "Lỗi tải ảnh!",
                        "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }

        String macb = txt_ma.getText();
        String mon1 = txt_mon1.getText();
        String mon2 = txt_mon2.getText();
        String mon3 = txt_mon3.getText();
        String mon4 = txt_mon4.getText();
        String loai = txt_loai.getText();

        int thu = Integer.parseInt(txt_thu.getText());
        float gia = Float.parseFloat(txt_gia.getText());

        //sửa khẩu phần
        if (chon == JOptionPane.YES_OPTION && suadoi == 1) {

            int row = jTable_combomonan.getSelectedRow();
            String QR = jTable_combomonan.getValueAt(row, 8).toString();

            int tam = DAO_KhauPhanAn.upDateDuLieu_ComBoMonAn(macb, mon1, mon2, mon3, mon4, loai, thu, gia, QR);
            int tam1 = DAO_KhauPhanAn.upDateDuLieu_ComBoMonAnHienThi(macb, mon1, mon2, mon3, mon4, loai, thu, gia, QR);
            if (tam == 1) {
                JOptionPane.showMessageDialog(rootPane, "Đã sửa khẩu phần ăn...");
                txt_mon1.setEnabled(false);
                txt_mon2.setEnabled(false);
                txt_mon3.setEnabled(false);
                txt_mon4.setEnabled(false);
                txt_loai.setEnabled(false);
                txt_thu.setEnabled(false);
                txt_gia.setEnabled(false);

                btn_xacnhan.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Sửa đổi khẩu phần thất bại...");
            }
        }

        //thiết lập khẩu phần
        if (chon == JOptionPane.YES_OPTION && thieilap == 1) {

            int tam = DAO_KhauPhanAn.themDuLieu_ComBoMonAn(mon1, mon2, mon3, mon4, loai, thu, gia, img.getName());
            if (tam == 1) {
                JOptionPane.showMessageDialog(rootPane, "Thiết lập khẩu phần thứ " + thu + " thành công...");               
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thiết lập khẩu phần thất bại...");
            }
        }

        txt_ma.setText("");
        txt_mon1.setText("");
        txt_mon1.setText("");
        txt_mon2.setText("");
        txt_mon3.setText("");
        txt_mon4.setText("");
        txt_loai.setText("");
        txt_thu.setText("");
        txt_gia.setText("");

        txt_mon1.setEnabled(false);
        txt_mon2.setEnabled(false);
        txt_mon3.setEnabled(false);
        txt_mon4.setEnabled(false);
        txt_loai.setEnabled(false);
        txt_thu.setEnabled(false);
        txt_gia.setEnabled(false);

        jLabel_qr.setIcon(null);

        btn_xacnhan.setEnabled(false);
        btn_huy.setEnabled(false);
        btn_taoqr.setEnabled(false);
        btn_themqr.setEnabled(false);
        img = null;
        showDuLieu_ComBoMonAnCu(dscbc);
    }//GEN-LAST:event_btn_xacnhanActionPerformed

    private void jTable_combomonanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_combomonanMouseClicked
        // TODO add your handling code here:
        int row = jTable_combomonan.getSelectedRow();

        String macb = jTable_combomonan.getValueAt(row, 0).toString();
        String mon1 = jTable_combomonan.getValueAt(row, 1).toString();
        String mon2 = jTable_combomonan.getValueAt(row, 2).toString();
        String mon3 = jTable_combomonan.getValueAt(row, 3).toString();
        String mon4 = jTable_combomonan.getValueAt(row, 4).toString();
        String loai = jTable_combomonan.getValueAt(row, 5).toString();
        String thu = jTable_combomonan.getValueAt(row, 6).toString();
        String gia = jTable_combomonan.getValueAt(row, 7).toString();
        String QR = jTable_combomonan.getValueAt(row, 8).toString();

        txt_ma.setText(macb);
        txt_loai.setText(loai);
        txt_gia.setText(gia);
        txt_thu.setText(thu);
        txt_mon1.setText(mon1);
        txt_mon2.setText(mon2);
        txt_mon3.setText(mon3);
        txt_mon4.setText(mon4);

        String imagePath = duongDanHinhAnh(QR);

        // Tạo ImageIcon từ ảnh
        ImageIcon originalIcon = new ImageIcon(imagePath);

        // Lấy kích thước của JLabel
        int labelWidth = 90;
        int labelHeight = 90;

        // Chuyển đổi ImageIcon thành Image để điều chỉnh kích thước
        Image originalImage = originalIcon.getImage();

        // Điều chỉnh kích thước của ảnh
        Image scaledImage = originalImage.getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);

        ImageIcon scaledIcon = new ImageIcon(scaledImage);
        // Tạo JLabel để hiển thị ảnh
        jLabel_qr.setIcon(scaledIcon);
    }//GEN-LAST:event_jTable_combomonanMouseClicked

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // TODO add your handling code here:
        txt_ma.setEditable(false);
        txt_mon1.setEnabled(false);
        txt_mon2.setEnabled(false);
        txt_mon3.setEnabled(false);
        txt_mon4.setEnabled(false);
        txt_loai.setEnabled(false);
        txt_thu.setEnabled(false);
        txt_gia.setEnabled(false);

        jLabel_qr.setIcon(null);

        btn_xacnhan.setEnabled(false);
        btn_huy.setEnabled(false);
        btn_taoqr.setEnabled(false);
        btn_themqr.setEnabled(false);
        img = null;
    }//GEN-LAST:event_btn_huyActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        btn_them.setEnabled(false);
        String macb = txt_ma.getText();
        int chon = JOptionPane.showConfirmDialog(null, "Bạn đã chắn chắn!",
                "Xác nhận", JOptionPane.YES_NO_OPTION);

        if (chon == JOptionPane.YES_OPTION && kpCu == 1) {
            int tam = DAO_KhauPhanAn.xoaMotKP_ComBoMonAn(macb);
            if (tam == 1) {
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công...");
                showDuLieu_ComBoMonAnCu(dscbc);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Xóa thất bại...");
            }
        }

        if (chon == JOptionPane.YES_OPTION && kpMoi == 1) {
            int tam = DAO_KhauPhanAn.xoaMotKP_ComBoMonAnHienThi(macb);
            if (tam == 1) {
                JOptionPane.showMessageDialog(rootPane, "Xóa thành công...");
                showDuLieu_ComBoMonAnHienThi(dscbht);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Xóa thất bại...");
            }
        }

        txt_ma.setText("");
        txt_mon1.setText("");
        txt_mon1.setText("");
        txt_mon2.setText("");
        txt_mon3.setText("");
        txt_mon4.setText("");
        txt_loai.setText("");
        txt_thu.setText("");
        txt_gia.setText("");

        jLabel_qr.setIcon(null);
        
        
        

    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        String macb = txt_ma.getText();
        String mon1 = txt_mon1.getText();
        String mon2 = txt_mon2.getText();
        String mon3 = txt_mon3.getText();
        String mon4 = txt_mon4.getText();
        String loai = txt_loai.getText();

        int row = jTable_combomonan.getSelectedRow();
        String QR = jTable_combomonan.getValueAt(row, 8).toString();

        int thu = Integer.parseInt(txt_thu.getText());
        float gia = Float.parseFloat(txt_gia.getText());
        int tam = DAO_KhauPhanAn.themDuLieu_ComBoMonAnHienThi(macb, mon1, mon2, mon3, mon4, loai, thu, gia, QR);

        if (tam == 1) {
            JOptionPane.showMessageDialog(rootPane, "Đã thêm Combo: '" + macb + "'" + " vào danh sách đăng kí!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Đã có khẩn phần này trong danh sách đăng kí...");
        }

    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_kpcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kpcuActionPerformed
        // TODO add your handling code here:

        kpCu = 1;
        kpMoi = 0;

        jTable_combomonan.setVisible(true);
        jTable_combomonan.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        tblData = new Vector();
        tblTitle = new Vector();
        tblModel = new DefaultTableModel();

        tblTitle.add("Mã Cb");
        tblTitle.add("Món 1");
        tblTitle.add("Món 2");
        tblTitle.add("Món 3");
        tblTitle.add("Món 4");
        tblTitle.add("Loại");
        tblTitle.add("Thứ");
        tblTitle.add("Giá tiền");
        tblTitle.add("QRCode");

        showDuLieu_ComBoMonAnCu(dscbc);

        btn_thietlap.setEnabled(true);
        btn_sua.setEnabled(true);
        btn_themvaokhauphanDK.setEnabled(true);
        btn_xoa.setEnabled(true);
        btn_xoa_all.setEnabled(true);

    }//GEN-LAST:event_btn_kpcuActionPerformed

    private void btn_khmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_khmoiActionPerformed
        // TODO add your handling code here:
        kpCu = 0;
        kpMoi = 1;

        btn_xoa.setEnabled(true);
        btn_xoa_all.setEnabled(true);

        jTable_combomonan.setVisible(true);
        jTable_combomonan.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblData = new Vector();
        tblTitle = new Vector();
        tblModel = new DefaultTableModel();

        tblTitle.add("Mã Cb");
        tblTitle.add("Món 1");
        tblTitle.add("Món 2");
        tblTitle.add("Món 3");
        tblTitle.add("Món 4");
        tblTitle.add("Loại");
        tblTitle.add("Thứ");
        tblTitle.add("Giá tiền");
        tblTitle.add("QRCode");

        showDuLieu_ComBoMonAnHienThi(dscbht);

        btn_thietlap.setEnabled(false);
        btn_sua.setEnabled(false);
        btn_themvaokhauphanDK.setEnabled(false);

        txt_ma.setText("");
        txt_mon1.setText("");
        txt_mon1.setText("");
        txt_mon2.setText("");
        txt_mon3.setText("");
        txt_mon4.setText("");
        txt_loai.setText("");
        txt_thu.setText("");
        txt_gia.setText("");

        txt_mon1.setEnabled(false);
        txt_mon2.setEnabled(false);
        txt_mon3.setEnabled(false);
        txt_mon4.setEnabled(false);
        txt_loai.setEnabled(false);
        txt_thu.setEnabled(false);
        txt_gia.setEnabled(false);

        btn_xacnhan.setEnabled(false);
        btn_huy.setEnabled(false);
    }//GEN-LAST:event_btn_khmoiActionPerformed

    private void btn_themvaokhauphanDKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themvaokhauphanDKActionPerformed
        // TODO add your handling code here:
        btn_them.setEnabled(true);
    }//GEN-LAST:event_btn_themvaokhauphanDKActionPerformed

    private static void copyToClipboard(String text) {
        StringSelection stringSelection = new StringSelection(text);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);
        //JOptionPane.showMessageDialog(null, "Message copied to clipboard!", "Copy Success", JOptionPane.INFORMATION_MESSAGE);
    }

    private void btn_taoqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taoqrActionPerformed
        // TODO add your handling code here:
        if (ktThongTinNhapVao() == false) {
            JOptionPane.showMessageDialog(rootPane, "Chưa nhập đủ thông tin ...");
            return;
        }

        String thongbao = "Thông tin khẩu phần ăn: \n"
                + "Món 1: " + txt_mon1.getText() + "\n"
                + "Món 2: " + txt_mon2.getText() + "\n"
                + "Món 3: " + txt_mon3.getText() + "\n"
                + "Món 4: " + txt_mon4.getText() + "\n"
                + "Loại: " + txt_loai.getText() + "\n"
                + "Thứ: " + txt_thu.getText() + "\n"
                + "Giá tiền: " + txt_gia.getText();

        JButton copyButton = new JButton("Copy");
        copyButton.addActionListener(e -> {
            copyToClipboard(thongbao);

            String url = "https://me-qr.com/vi/qr-code-generator/text";
            try {
                Desktop.getDesktop().browse(new URI(url));
            } catch (Exception ex) {
                ex.printStackTrace();
            }

            // Đóng hộp thoại thông báo (JOptionPane)
            Window[] windows = Window.getWindows();
            for (Window window : windows) {
                if (window instanceof JDialog) {
                    JDialog dialog = (JDialog) window;
                    if (dialog.getContentPane().getComponentCount() == 1
                            && dialog.getContentPane().getComponent(0) instanceof JOptionPane) {
                        dialog.dispose();
                    }
                }
            }
        });

        Object[] options = {copyButton};
        int result = JOptionPane.showOptionDialog(null, thongbao, "Thông tin khẩu phẩn",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);

        if (result == 0) {
            // User clicked the Copy button
            copyToClipboard("Thông báo 3");
        }
    }//GEN-LAST:event_btn_taoqrActionPerformed

    private void btn_themqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themqrActionPerformed
        // TODO add your handling code here:
        // Mở hộp thoại chọn tệp và thiết lập bộ lọc
        JFileChooser fileChooser = new JFileChooser();
        // Bộ lọc tệp chỉ hiển thị các tệp PNG  
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PNG Images", "png");
        fileChooser.setFileFilter(filter);
        fileChooser.setMultiSelectionEnabled(false); // chỉ cho phép chọn 1 file trong 1 thời điểm

        // Đặt tiêu đề cho hộp thoại
        fileChooser.setDialogTitle("Chọn file");

        int kq = fileChooser.showOpenDialog(this);

        if (kq == JFileChooser.APPROVE_OPTION) {
            // Lấy tệp ảnh được chọn
            img = fileChooser.getSelectedFile();

            if (img == null) {
                JOptionPane.showMessageDialog(rootPane, "Lỗi tải hình ảnh!");
                return;
            } else {
                // Tạo ImageIcon từ ảnh
                String path_img = img.getAbsolutePath();
                fileName = img.getName();

                ImageIcon originalIcon = new ImageIcon(path_img);

                // Lấy kích thước của JLabel
                int labelWidth = 90;
                int labelHeight = 90;

                // Chuyển đổi ImageIcon thành Image để điều chỉnh kích thước
                Image originalImage = originalIcon.getImage();

                // Điều chỉnh kích thước của ảnh
                Image scaledImage = originalImage.getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);

                ImageIcon scaledIcon = new ImageIcon(scaledImage);
                // Tạo JLabel để hiển thị ảnh
                jLabel_qr.setIcon(scaledIcon);
            }
        }
    }//GEN-LAST:event_btn_themqrActionPerformed

    private void jTable_combomonanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_combomonanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_combomonanMouseEntered

    private void btn_quaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quaylaiActionPerformed
        // TODO add your handling code here:
        Managanent_GUI fr = new Managanent_GUI();
        fr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_quaylaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLi_KPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLi_KPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLi_KPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_QuanLi_KPA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_QuanLi_KPA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_khmoi;
    private javax.swing.JButton btn_kpcu;
    private javax.swing.JButton btn_quaylai;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_taoqr;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_themqr;
    private javax.swing.JButton btn_themvaokhauphanDK;
    private javax.swing.JButton btn_thietlap;
    private javax.swing.JButton btn_xacnhan;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JButton btn_xoa_all;
    private javax.swing.JButton jButton6;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_qr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_combomonan;
    private javax.swing.JTextField txt_gia;
    private javax.swing.JTextField txt_loai;
    private javax.swing.JTextField txt_ma;
    private javax.swing.JTextField txt_mon1;
    private javax.swing.JTextField txt_mon2;
    private javax.swing.JTextField txt_mon3;
    private javax.swing.JTextField txt_mon4;
    private javax.swing.JTextField txt_thu;
    // End of variables declaration//GEN-END:variables
}
