/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.GiamSatSA_DAO;
import DAO.NhanVien_DAO;
import POJO.DBA_AUDIT_TRAIL;
import POJO.NhanVien_POJO;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class GiamSatNhanVienBangSA_GUI extends javax.swing.JFrame {
    Vector tblData2 = new Vector();
    Vector tblTitle2 = new Vector();
    DefaultTableModel tblModel2;
    
    static ArrayList<NhanVien_POJO> dsnv = NhanVien_DAO.LayThongTinNhanVien();
    static ArrayList<DBA_AUDIT_TRAIL> dat = GiamSatSA_DAO.LayThongTinGiamSat();

    /**
     * Creates new form frm_GiamSatSuDungSA
     */
    public GiamSatNhanVienBangSA_GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        bangGiamSatNV();
        layDuLieuGiamSat(dat);
        
        txt_quyen.setText(Login_GUI.chucvu_User);
        txt_quyen.setHorizontalAlignment(SwingConstants.CENTER);
    }

//    private GiamSatNhanVienBangSA_GUI() {
//    }
    public void bangGiamSatNV() {
        tblTitle2.add("username");
        tblTitle2.add("timestamp");
        tblTitle2.add("obj_name");
        tblTitle2.add("action_name");
    }
    public void layDuLieuGiamSat(ArrayList<DBA_AUDIT_TRAIL> dat) {
        tblData2.removeAllElements();
        for (DBA_AUDIT_TRAIL a : dat) {
            Vector v = new Vector();
            v.add(a.getUsername());
            v.add(a.getTimestamp());
            v.add(a.getObj_name());
            v.add(a.getAction_name());
            tblData2.add(v);
        }
        tb_GiamSatNV.setModel(new DefaultTableModel(tblData2, tblTitle2));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_maNV = new javax.swing.JTextField();
        btn_ApDungTheoUser = new javax.swing.JButton();
        txt_quyen = new javax.swing.JTextField();
        btn_troVe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_GiamSatNV = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rdb_selectTable = new javax.swing.JRadioButton();
        rdb_updateTable = new javax.swing.JRadioButton();
        rdb_insertTable = new javax.swing.JRadioButton();
        rdb_deleteTable = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_ApDungTheoUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_ApDungTheoUser.setText("Áp dụng theo User");
        btn_ApDungTheoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ApDungTheoUserActionPerformed(evt);
            }
        });

        txt_quyen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_quyen.setEnabled(false);

        btn_troVe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_troVe.setText("Trở về");
        btn_troVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_troVeActionPerformed(evt);
            }
        });

        tb_GiamSatNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_GiamSatNVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_GiamSatNV);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mã nhân viên:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        rdb_selectTable.setText("Select table");

        rdb_updateTable.setText("Update table");

        rdb_insertTable.setText("Insert table");

        rdb_deleteTable.setText("Delete table");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdb_selectTable, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdb_updateTable, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdb_insertTable, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdb_deleteTable, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdb_selectTable)
                .addGap(18, 18, 18)
                .addComponent(rdb_updateTable)
                .addGap(18, 18, 18)
                .addComponent(rdb_insertTable)
                .addGap(18, 18, 18)
                .addComponent(rdb_deleteTable)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_maNV, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ApDungTheoUser, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_troVe, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_quyen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_quyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_maNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ApDungTheoUser))
                        .addGap(60, 60, 60)
                        .addComponent(btn_troVe)
                        .addGap(36, 36, 36))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ApDungTheoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ApDungTheoUserActionPerformed
        // TODO add your handling code here:
        String maNV = txt_maNV.getText().trim();
        //String table = txt_tenBang.getText().trim();
        
        if(rdb_selectTable.isSelected()==true){
            String sql = "AUDIT SELECT TABLE BY "+maNV+"";         
            if(NhanVien_DAO.ThemXoaSuaNhanVien(sql) == 0 ){            
                JOptionPane.showMessageDialog(this,"Thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);             
            }
        }
        if(rdb_updateTable.isSelected()==true){
            String sql = "AUDIT UPDATE TABLE BY "+maNV+"";         
            if(NhanVien_DAO.ThemXoaSuaNhanVien(sql) == 0 ){            
                JOptionPane.showMessageDialog(this,"Thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);             
            }
        }
        if(rdb_insertTable.isSelected()==true){
            String sql = "AUDIT INSERT TABLE BY "+maNV+"";         
            if(NhanVien_DAO.ThemXoaSuaNhanVien(sql) == 0 ){            
                JOptionPane.showMessageDialog(this,"Thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);             
            }
        }
        if(rdb_deleteTable.isSelected()==true){
            String sql = "AUDIT DELETE TABLE BY "+maNV+"";         
            if(NhanVien_DAO.ThemXoaSuaNhanVien(sql) == 0 ){            
                JOptionPane.showMessageDialog(this,"Thành công","Thông báo", JOptionPane.INFORMATION_MESSAGE);             
            }
        }
    }//GEN-LAST:event_btn_ApDungTheoUserActionPerformed

    private void btn_troVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_troVeActionPerformed
        // TODO add your handling code here:
        Managanent_GUI qlnv = new Managanent_GUI();
        qlnv.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_troVeActionPerformed

    private void tb_GiamSatNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_GiamSatNVMouseClicked
        int i = tb_GiamSatNV.getSelectedRow();
        String manv = tb_GiamSatNV.getValueAt(i, 0).toString().trim();

        txt_maNV.setText(manv);
    }//GEN-LAST:event_tb_GiamSatNVMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiamSatNhanVienBangSA_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiamSatNhanVienBangSA_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiamSatNhanVienBangSA_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiamSatNhanVienBangSA_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiamSatNhanVienBangSA_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ApDungTheoUser;
    private javax.swing.JButton btn_troVe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdb_deleteTable;
    private javax.swing.JRadioButton rdb_insertTable;
    private javax.swing.JRadioButton rdb_selectTable;
    private javax.swing.JRadioButton rdb_updateTable;
    private javax.swing.JTable tb_GiamSatNV;
    private javax.swing.JTextField txt_maNV;
    private javax.swing.JTextField txt_quyen;
    // End of variables declaration//GEN-END:variables
}
