/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.DAO_XacThuc;
import DAO.DBConnect;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Login_GUI extends javax.swing.JFrame {

    private int loginAttempts = 0;
    public static String loggedInUser;

    public static String chucvu_User;

    public static String kitu_User;

    /**
     * Creates new form Login_GUI
     */
    public Login_GUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Login");

        System.out.println("Chào Sơn ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        ckb_showPass = new javax.swing.JCheckBox();
        btn_login = new javax.swing.JButton();
        txt_pass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txt_database = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_localhost = new javax.swing.JTextField();
        lbl_phuongthuc2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_port = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        jLabel1.setText("LOGIN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Username:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Password:");

        txt_user.setText("NV003");

        ckb_showPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ckb_showPass.setText("Show password");
        ckb_showPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckb_showPassActionPerformed(evt);
            }
        });

        btn_login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_login.setText("LOGIN");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        txt_pass.setText("NV003");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Database:");

        txt_database.setText("DBHSBT");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setText("Localhost:");

        txt_localhost.setText("26.205.208.226");

        lbl_phuongthuc2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbl_phuongthuc2.setForeground(new java.awt.Color(51, 102, 255));
        lbl_phuongthuc2.setText("Xác thực khuôn mặt");
        lbl_phuongthuc2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_phuongthuc2MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Phương Thức Khác:");

        txt_port.setText("1521");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setText("Port:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_pass)
                            .addComponent(txt_database)
                            .addComponent(txt_localhost)
                            .addComponent(txt_user)
                            .addComponent(txt_port, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(ckb_showPass)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_phuongthuc2)))))
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(txt_localhost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_database, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lbl_phuongthuc2))
                    .addComponent(ckb_showPass))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btn_login)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        String localhost, port, database, user, pass;
        localhost = txt_localhost.getText();
        port = txt_port.getText();
        database = txt_database.getText();
        user = txt_user.getText();
        pass = txt_pass.getText();
        if ("sys".equals(user) || "SYS".equals(user)) {
            try {
                DBConnect.localhost = localhost;
                DBConnect.port = port;
                DBConnect.database = database;
                DBConnect.user = user;
                DBConnect.pass = pass;
                if (DBConnect.Connect()) {
                    JOptionPane.showMessageDialog(rootPane, "Đăng nhập thành công user " + user);
                    loggedInUser = user;
                    TrangChu_GUI qlc = new TrangChu_GUI();
                    qlc.setVisible(true);
                    dispose();
                    this.dispose();
                } else {
                    loginAttempts++; // Tăng số lần nhập sai
                    if (loginAttempts < 4) {
                        JOptionPane.showMessageDialog(rootPane, "Thông tin User/Password chưa đúng (Lần " + loginAttempts + "/3)");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Tài khoản đã bị khóa");
                    }
                }
            } catch (Exception e) {
                DBConnect.getInstance().close(); // Đóng kết nối
                System.out.println("Kết nối đã đóng");
            }
        } else {
            try {
                DBConnect.localhost = localhost;
                DBConnect.port = port;
                DBConnect.database = database;
                DBConnect.user = user;
                DBConnect.pass = pass;

//                String Url2 = "jdbc:oracle:thin:@localhost:1521";
//                String user2 = "NV001";
//                String pass2 = "NV001";
//                String database2 = "orcl";

                String Url2 = "jdbc:oracle:thin:@26.205.208.226:1521"; // IP dung để kết nối tới máy chủ
                String user2 = "NV001";
                String pass2 = "NV001";
                String database2 = "DBHSBT";

                try {
                    if (user2.equals("sys") || user2.equals("SYS")) {
                        user2 += " as sysdba";
                    }
                    Connection conn2 = DriverManager.getConnection(Url2 + ":" + database2, user2, pass2);
                    Statement statement = conn2.createStatement();
                    // Sử dụng CallableStatement để gọi thủ tục kiểm tra trạng thái
                    String sql = "{call sys.kiem_tra_trang_thai(?, ?) }";
                    CallableStatement cs = conn2.prepareCall(sql);
                    cs.registerOutParameter(2, Types.VARCHAR);
                    cs.setString(1, user);
                    cs.execute();
                    String status = cs.getString(2);

                    String sql2 = "{call NV001.LayHaiKiTuDau(?, ?) }";
                    CallableStatement cs2 = conn2.prepareCall(sql2);
                    cs2.registerOutParameter(2, Types.VARCHAR);
                    cs2.setString(1, user);
                    cs2.execute();
                    String kitu = cs2.getString(2);
                    kitu_User = kitu;

                    if (!"HS".equals(kitu_User)) {
                        String sql1 = "{call NV001.LAYCHUCVU(?, ?) }";
                        CallableStatement cs1 = conn2.prepareCall(sql1);
                        cs1.registerOutParameter(2, Types.VARCHAR);
                        cs1.setString(1, user);
                        cs1.execute();
                        String chucvu = cs1.getString(2);
                        //System.out.println("Chuc vu: " + chucvu);
                        chucvu_User = chucvu;
                    }

                    // Kiểm tra trạng thái tài khoản
                    if ("LOCKED".equals(status) || "LOCKED(TIMED)".equals(status)) {
                        JOptionPane.showMessageDialog(rootPane, "Tài khoản đã bị khóa");
                    } else {
                        DBConnect connectionDB = new DBConnect();
                        Connection conn = connectionDB.GetConnect();
                        if (DBConnect.Connect()) {
                            JOptionPane.showMessageDialog(rootPane, "Đăng nhập thành công user " + user);
                            loggedInUser = user;
                            TrangChu_GUI qlc = new TrangChu_GUI();
                            qlc.setVisible(true);
                            dispose();
                            this.dispose();
                        } else {
                            loginAttempts++; // Tăng số lần nhập sai
                            if (loginAttempts < 4) {
                                JOptionPane.showMessageDialog(rootPane, "Thông tin User/Password chưa đúng (Lần " + loginAttempts + "/3)");
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "Tài khoản đã bị khóa");
                            }
                        }
                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Lỗi: " + ex.getMessage());
                }
            } catch (Exception e) {
                e.printStackTrace(); // In thông tin lỗi vào console để xác định vấn đề cụ thể
                DBConnect.getInstance().close(); // Đóng kết nối
                JOptionPane.showMessageDialog(rootPane, "Lỗi kết nối đến cơ sở dữ liệu");
            }
        }


    }//GEN-LAST:event_btn_loginActionPerformed


    private void ckb_showPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckb_showPassActionPerformed
        // TODO add your handling code here:
        if (ckb_showPass.isSelected()) {
            txt_pass.setEchoChar((char) 0);
        } else {
            txt_pass.setEchoChar('*');
        }
    }//GEN-LAST:event_ckb_showPassActionPerformed
    private static void runCommand(String pythonScriptPath, String pythonScriptFolder, String pythonCommand) {
        try {
            // Tạo một ProcessBuilder           
            ProcessBuilder processBuilder = new ProcessBuilder(pythonCommand, pythonScriptPath);
            // Đặt thư mục làm việc cho ProcessBuilder

            processBuilder.directory(new File(pythonScriptFolder));
            // Redirect standard output to Java application
            processBuilder.redirectErrorStream(true);

            // Bắt đầu quá trình
            Process process = processBuilder.start();

            // Đọc output từ quá trình
            InputStream inputStream = process.getInputStream();
            BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream));
            String line;
            while ((line = reader.readLine()) != null) {
                System.out.println(line);
            }
            // Đợi quá trình kết thúc
            int exitCode = process.waitFor();
            System.out.println("Exited with error code " + exitCode);

        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }
    }

    private void lbl_phuongthuc2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_phuongthuc2MouseClicked
        // TODO add your handling code here:        
        String pythonScriptPath = "C:\\Users\\SONDAY\\XacThucKhuonMat\\MiAI_FaceRecog_3\\src\\face_rec_cam.py";
        // Đường dẫn đến thư mục chứa file Python
        String pythonScriptFolder = "C:\\Users\\SONDAY\\XacThucKhuonMat\\MiAI_FaceRecog_3";

        // Lệnh Python
        String pythonCommand = "python";
        runCommand(pythonScriptPath, pythonScriptFolder, pythonCommand);

        String localhost, port, database, user, pass;
        localhost = txt_localhost.getText();
        port = txt_port.getText();
        database = txt_database.getText();
        user = "NV001";
        pass = "NV001";

        try {
            DBConnect.localhost = localhost;
            DBConnect.port = port;
            DBConnect.database = database;
            DBConnect.user = user;
            DBConnect.pass = pass;
            if (DBConnect.Connect()) {
                System.out.println("Thành công...");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Lỗi hệ thông! ");
            }
        } catch (Exception e) {
            DBConnect.getInstance().close(); // Đóng kết nối
            System.out.println("Kết nối đã đóng");
        }

        //---------------------------------------------
        String filePath = "C:\\Users\\SONDAY\\XacThucKhuonMat\\MiAI_FaceRecog_3\\xacthuckhuongmat.txt";

        String thongtin = "";
        try (BufferedReader reader = new BufferedReader(new FileReader(filePath))) {
            StringBuilder content = new StringBuilder();
            String line;

            // Đọc từng dòng và thêm vào StringBuilder
            while ((line = reader.readLine()) != null) {
                content.append(line).append("\n");
            }

            thongtin = content.toString().trim();

            // Hiển thị nội dung file
            //JOptionPane.showMessageDialog(rootPane, thongtin);
            System.out.println("Thông tin: " + thongtin);
        } catch (IOException e) {
            e.printStackTrace();
            //JOptionPane.showMessageDialog(this, "Không thể đọc file", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

        if (thongtin.equals("KHÔNG XÁC ĐỊNH") == true || thongtin.equals("") == true) {
            JOptionPane.showMessageDialog(rootPane, "Không xác định được tài khoản...");
            txt_user.setText(thongtin);
            return;
        } else {
            String pass1 = DAO_XacThuc.LayThongTinPass(thongtin);
            if (pass1 != null) {
                //JOptionPane.showMessageDialog(rootPane, pass1);
                System.out.println("Password đã lấy: " + pass1);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Xác thực không thành công...1");
            }

            // String kq = DAO.DAO_XacThuc.giaiMaPass(pass1);
            if (pass1 != null) {
                //JOptionPane.showMessageDialog(rootPane, kq);
                System.out.println("Kết quả giải mã: " + pass1);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Xác thực không thành công..2");
            }

            txt_user.setText(thongtin);
            txt_pass.setText(pass1);
        }
    }//GEN-LAST:event_lbl_phuongthuc2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JCheckBox ckb_showPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_phuongthuc2;
    private javax.swing.JTextField txt_database;
    private javax.swing.JTextField txt_localhost;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_port;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
