/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.ChiTietDeThi_DAO;
import DAO.DeThi_DAO;
import DAO.MonHoc_DAO;
import POJO.ChiTietDeThi_POJO;
import POJO.DeThi;
import POJO.MonHoc;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TAN HUY
 */
public class ThongTinThiOnline_GUI extends javax.swing.JFrame {
    public static String maMonHoc;
    public static String maDeThi;
    public static String maHocSinh;
    Vector tblData = new Vector();
    Vector tblTitle = new Vector();
    DefaultTableModel tblModel;
    
    static ArrayList<MonHoc> dsmh = MonHoc_DAO.LayThongTinMonHoc();
    static ArrayList<DeThi> dsdt = DeThi_DAO.LayThongTin_DeThi();
    
    /**
     * Creates new form ThongTinThiOnline_GUI
     */
    public ThongTinThiOnline_GUI() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        setTitle("Thông Tin Học Sinh");
        
        txt_maHocSinh.setText(Login_GUI.loggedInUser);
        
        loadComboBoxMonHoc();
        loadComboBoxDeThi();
        
    }
     public void bangMonHoc() {
        tblTitle.add("MAMH");
        tblTitle.add("TENMH");
        tblTitle.add("MALOP");
    }
    public void loadComboBoxMonHoc() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (MonHoc mh : dsmh) {
            model.addElement(mh.getMaMH());
        }
        cbo_monHoc.setModel(model);
        cbo_monHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBox cb = (JComboBox) evt.getSource();
                // Lấy giá trị đã chọn và gán vào biến maMonHoc
                maMonHoc = (String) cb.getSelectedItem();
            }
        });
    }
    public void loadComboBoxDeThi() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (DeThi dt : dsdt) {
            model.addElement(dt.getMaDeThi());
        }
        cbo_deThi.setModel(model);
        cbo_deThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JComboBox cb = (JComboBox) evt.getSource();
                // Lấy giá trị đã chọn và gán vào biến maDeThi
                maDeThi = (String) cb.getSelectedItem();
                // Gọi phương thức để hiển thị thông tin khi chọn mã đề từ combobox
                hienThiThongTinChiTietDeThi(maDeThi);
            }
        });
    }

    // Trong phương thức hienThiThongTinChiTietDeThi(String maDe)
    public void hienThiThongTinChiTietDeThi(String maDe) {
        // Gọi phương thức trong DAO để lấy thông tin chi tiết đề thi

        ArrayList<ChiTietDeThi_POJO> dsThongTin = ChiTietDeThi_DAO.LayThongTinChiTietDeThi(maDe);

        // Kiểm tra xem danh sách thông tin có dữ liệu không
        if (!dsThongTin.isEmpty()) {
            // Lấy thông tin từ phần tử đầu tiên của danh sách (vì ta chỉ cần hiển thị thông tin của một mã đề)
            ChiTietDeThi_POJO thongTin = dsThongTin.get(0);

            // Hiển thị thông tin lên các text field
            txt_tgThi.setText(thongTin.getTHOIGIANTHI());
            txt_tgBatDau.setText(thongTin.getTHOIGIANBATDAU());
            txt_tgKetThuc.setText(thongTin.getTHOIGIANKETTHUC());
        } else {
            // Nếu không có thông tin, đặt các text field về trống
            txt_tgThi.setText("Khong lay dc dl");
            txt_tgBatDau.setText("");
            txt_tgKetThuc.setText("");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_tgThi = new javax.swing.JTextField();
        txt_tgBatDau = new javax.swing.JTextField();
        txt_tgKetThuc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbo_monHoc = new javax.swing.JComboBox<>();
        txt_maHocSinh = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbo_deThi = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btn_thi = new javax.swing.JButton();
        btn_xemDiem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btn_quaylai1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Học Sinh"));

        jLabel1.setText("Mã Học Sinh:");

        txt_tgThi.setEditable(false);

        txt_tgBatDau.setEditable(false);

        txt_tgKetThuc.setEditable(false);

        jLabel4.setText("Môn Thi:");

        jLabel5.setText("Thời Gian Thi:");

        jLabel6.setText("Thời Gian Bắt Đầu:");

        jLabel7.setText("Thời Gian Kết Thúc:");

        jLabel9.setText("Đề Thi:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_tgThi)
                    .addComponent(txt_tgBatDau)
                    .addComponent(txt_tgKetThuc)
                    .addComponent(cbo_monHoc, 0, 315, Short.MAX_VALUE)
                    .addComponent(txt_maHocSinh)
                    .addComponent(cbo_deThi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_maHocSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbo_monHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbo_deThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_tgThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_tgBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_tgKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btn_thi.setBackground(new java.awt.Color(204, 255, 255));
        btn_thi.setText("Thi");
        btn_thi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thiActionPerformed(evt);
            }
        });

        btn_xemDiem.setBackground(new java.awt.Color(204, 255, 255));
        btn_xemDiem.setText("Xem Điểm");
        btn_xemDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xemDiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_xemDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_thi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(btn_thi)
                .addGap(35, 35, 35)
                .addComponent(btn_xemDiem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Bài Thi Trắc Nghiệm");

        btn_quaylai1.setBackground(new java.awt.Color(204, 204, 204));
        btn_quaylai1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_quaylai1.setForeground(new java.awt.Color(255, 51, 0));
        btn_quaylai1.setText("QUAY LẠI");
        btn_quaylai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quaylai1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_quaylai1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(222, 222, 222))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(btn_quaylai1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_thiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thiActionPerformed
        // TODO add your handling code here:
        
        // Gán giá trị từ txt_maHocSinh vào biến maHocSinh
        maHocSinh = txt_maHocSinh.getText();
        // Kiểm tra xem có giá trị nào được chọn trong combo box không
        if (maMonHoc == null || maHocSinh == null || maDeThi == null) {
            // Nếu một trong hai là null, hiển thị thông báo và không thực hiện hành động tiếp theo
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin để bắt đầu thi!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Gán giá trị từ txt_maHocSinh vào biến maHocSinh
        maHocSinh = txt_maHocSinh.getText();
        
        ThiTracNghiem_GUI thiOnline = new ThiTracNghiem_GUI();
        thiOnline.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_thiActionPerformed

    private void btn_xemDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xemDiemActionPerformed
        // TODO add your handling code here:
        DiemSo_GUI diemso = new DiemSo_GUI();
        diemso.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_xemDiemActionPerformed

    private void btn_quaylai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quaylai1ActionPerformed
        Managanent_GUI frm = new Managanent_GUI();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_quaylai1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinThiOnline_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinThiOnline_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinThiOnline_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinThiOnline_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinThiOnline_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_quaylai1;
    private javax.swing.JButton btn_thi;
    private javax.swing.JButton btn_xemDiem;
    private javax.swing.JComboBox<String> cbo_deThi;
    private javax.swing.JComboBox<String> cbo_monHoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_maHocSinh;
    private javax.swing.JTextField txt_tgBatDau;
    private javax.swing.JTextField txt_tgKetThuc;
    private javax.swing.JTextField txt_tgThi;
    // End of variables declaration//GEN-END:variables
}
