/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author SONDAY
 */
import DAO.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.math.BigInteger;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class v3_TaoKhoaVaKy extends javax.swing.JFrame {

    /**
     * Creates new form v3_TaoKhoaVaKy
     */
    static int kich_thuoc_key;
    static AlgorithmRSA rsa;

    public v3_TaoKhoaVaKy() {
        initComponents();
        this.setLocationRelativeTo(null);

        kich_thuoc_key = Integer.parseInt((String) cbo_chon_kichthuockhoa.getSelectedItem());
        rsa = new AlgorithmRSA();
        rsa.TaoKhoaRSA(kich_thuoc_key);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbo_chon_kichthuockhoa = new javax.swing.JComboBox<>();
        btn_luu_khoabimat = new javax.swing.JButton();
        btn_taokhoa = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_area_khoabimat_DUOCTAO = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btn_luu_khoacongkhai = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_area_khoacongkhai_DUOCTAO = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn_chon_file_canky = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_area_filecanky_CHON = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        btn_chon_file_privatekey = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txt_area_khoabimat_CHON = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_area_SHA_KY = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txt_area_chukyso_KY = new javax.swing.JTextArea();
        btn_luu_chukyso = new javax.swing.JButton();
        btn_kyso = new javax.swing.JButton();
        btn_RESET = new java.awt.Button();
        btn_move_xacminh = new java.awt.Button();
        btn_quaylai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("TẠO KHOÁ VÀ KÝ SỐ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TẠO KHOÁ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Kích thước:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Khoá bí mật:");

        cbo_chon_kichthuockhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "256", "512", "1024", "2048", "3072" }));
        cbo_chon_kichthuockhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_chon_kichthuockhoaActionPerformed(evt);
            }
        });

        btn_luu_khoabimat.setBackground(new java.awt.Color(153, 255, 255));
        btn_luu_khoabimat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_luu_khoabimat.setText("Lưu khoá bí mật");
        btn_luu_khoabimat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luu_khoabimatActionPerformed(evt);
            }
        });

        btn_taokhoa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_taokhoa.setText("TẠO KHOÁ");
        btn_taokhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taokhoaActionPerformed(evt);
            }
        });

        txt_area_khoabimat_DUOCTAO.setColumns(20);
        txt_area_khoabimat_DUOCTAO.setRows(5);
        jScrollPane3.setViewportView(txt_area_khoabimat_DUOCTAO);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Khoá công khai:");

        btn_luu_khoacongkhai.setBackground(new java.awt.Color(153, 255, 255));
        btn_luu_khoacongkhai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_luu_khoacongkhai.setText("Lưu khoá công khai");
        btn_luu_khoacongkhai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luu_khoacongkhaiActionPerformed(evt);
            }
        });

        txt_area_khoacongkhai_DUOCTAO.setColumns(20);
        txt_area_khoacongkhai_DUOCTAO.setRows(5);
        jScrollPane4.setViewportView(txt_area_khoacongkhai_DUOCTAO);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(33, 33, 33)
                        .addComponent(cbo_chon_kichthuockhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_taokhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(btn_luu_khoabimat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_luu_khoacongkhai, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_luu_khoabimat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_luu_khoacongkhai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbo_chon_kichthuockhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_taokhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "KÝ SỐ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Chọn file cần ký:");

        btn_chon_file_canky.setBackground(new java.awt.Color(153, 255, 255));
        btn_chon_file_canky.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_chon_file_canky.setText("Chọn");
        btn_chon_file_canky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chon_file_cankyActionPerformed(evt);
            }
        });

        txt_area_filecanky_CHON.setColumns(20);
        txt_area_filecanky_CHON.setRows(5);
        jScrollPane5.setViewportView(txt_area_filecanky_CHON);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Chọn file private key:");

        btn_chon_file_privatekey.setBackground(new java.awt.Color(153, 255, 255));
        btn_chon_file_privatekey.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_chon_file_privatekey.setText("Chọn");
        btn_chon_file_privatekey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chon_file_privatekeyActionPerformed(evt);
            }
        });

        txt_area_khoabimat_CHON.setColumns(20);
        txt_area_khoabimat_CHON.setRows(5);
        jScrollPane7.setViewportView(txt_area_khoabimat_CHON);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("SHA:");

        txt_area_SHA_KY.setColumns(20);
        txt_area_SHA_KY.setRows(5);
        jScrollPane6.setViewportView(txt_area_SHA_KY);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Chữ ký số được tạo:");

        txt_area_chukyso_KY.setColumns(20);
        txt_area_chukyso_KY.setRows(5);
        jScrollPane8.setViewportView(txt_area_chukyso_KY);

        btn_luu_chukyso.setBackground(new java.awt.Color(153, 255, 255));
        btn_luu_chukyso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_luu_chukyso.setText("Lưu chữ ký số");
        btn_luu_chukyso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luu_chukysoActionPerformed(evt);
            }
        });

        btn_kyso.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_kyso.setText("KÝ SỐ");
        btn_kyso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kysoActionPerformed(evt);
            }
        });

        btn_RESET.setBackground(new java.awt.Color(255, 255, 0));
        btn_RESET.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_RESET.setLabel("Reset");
        btn_RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RESETActionPerformed(evt);
            }
        });

        btn_move_xacminh.setBackground(new java.awt.Color(153, 255, 255));
        btn_move_xacminh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_move_xacminh.setLabel("-> XÁC MINH");
        btn_move_xacminh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_move_xacminhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(btn_chon_file_canky, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_chon_file_privatekey, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_kyso, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btn_move_xacminh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_luu_chukyso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_RESET, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_luu_chukyso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(btn_RESET, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_chon_file_canky, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_chon_file_privatekey, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_kyso, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(btn_move_xacminh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(16, 16, 16))
        );

        btn_quaylai.setText("Trở về");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(486, 486, 486)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_quaylai)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_quaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_taokhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taokhoaActionPerformed
        // TODO add your handling code here:
        rsa.TaoKhoaRSA(kich_thuoc_key);
        txt_area_khoabimat_DUOCTAO.setText(rsa.getKhoa_cong_khai().toString());
        txt_area_khoacongkhai_DUOCTAO.setText(rsa.getKhoa_bi_mat().toString());
        rsa.setKhoa_bi_mat(new BigInteger(txt_area_khoabimat_DUOCTAO.getText()));
        rsa.setKhoa_cong_khai(new BigInteger(txt_area_khoacongkhai_DUOCTAO.getText()));

        btn_chon_file_canky.setEnabled(true);
        btn_kyso.setEnabled(true);
        btn_luu_khoabimat.setEnabled(true);
        btn_luu_khoacongkhai.setEnabled(true);
    }//GEN-LAST:event_btn_taokhoaActionPerformed

    private void btn_luu_khoabimatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luu_khoabimatActionPerformed
        // TODO add your handling code here:
        // Kiểm tra xem vùng văn bản khóa bí mật có trống không
        if (txt_area_khoabimat_DUOCTAO.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Khóa bí mật chưa được tạo. Hãy tạo trước khi lưu.", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return; // Dừng hàm nếu chưa tạo khóa bí mật
        }

        // Lấy khóa bí mật từ vùng văn bản
        String khoaBiMat = txt_area_khoabimat_DUOCTAO.getText();

        // Mở hộp thoại chọn vị trí lưu file
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Chọn vị trí lưu file");

        // Bộ lọc cho phép chọn tệp có định dạng .txt
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Tệp văn bản (*.txt)", "txt");
        chooser.setFileFilter(filter);

        // Hiển thị hộp thoại lưu và lấy kết quả
        int userSelection = chooser.showSaveDialog(null);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            // Lấy đường dẫn đến file được chọn
            File fileToSave = chooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();

            // Kiểm tra nếu đường dẫn không có định dạng .txt, thêm phần mở rộng .txt
            if (!filePath.toLowerCase().endsWith(".txt")) {
                filePath += ".txt";
            }

            // Lưu khóa bí mật vào file .txt
            try {
                java.nio.file.Files.write(java.nio.file.Paths.get(filePath), khoaBiMat.getBytes());
                JOptionPane.showMessageDialog(null, "Lưu khóa bí mật thành công vào " + filePath);
            } catch (IOException ex) {
                Logger.getLogger(v3_TaoKhoaVaKy.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Lỗi khi lưu file", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_luu_khoabimatActionPerformed

    private void btn_luu_khoacongkhaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luu_khoacongkhaiActionPerformed
        // TODO add your handling code here:
        // Kiểm tra xem vùng văn bản khóa công khai có trống không
        if (txt_area_khoacongkhai_DUOCTAO.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Khóa công khai chưa được tạo. Hãy tạo trước khi lưu.", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return; // Dừng hàm nếu chưa tạo khóa công khai
        }

        // Lấy khóa công khai từ vùng văn bản
        String khoaCongKhai = txt_area_khoacongkhai_DUOCTAO.getText();

        // Mở hộp thoại chọn vị trí lưu file
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Chọn vị trí lưu file");

        // Bộ lọc cho phép chọn tệp có định dạng .txt
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Tệp văn bản (*.txt)", "txt");
        chooser.setFileFilter(filter);

        // Hiển thị hộp thoại lưu và lấy kết quả
        int userSelection = chooser.showSaveDialog(null);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            // Lấy đường dẫn đến file được chọn
            File fileToSave = chooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();

            // Kiểm tra nếu đường dẫn không có định dạng .txt, thêm phần mở rộng .txt
            if (!filePath.toLowerCase().endsWith(".txt")) {
                filePath += ".txt";
            }

            // Lưu khóa công khai vào file .txt
            try {
                java.nio.file.Files.write(java.nio.file.Paths.get(filePath), khoaCongKhai.getBytes());
                JOptionPane.showMessageDialog(null, "Lưu khóa công khai thành công vào " + filePath);
            } catch (IOException ex) {
                Logger.getLogger(v3_TaoKhoaVaKy.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Lỗi khi lưu file", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_luu_khoacongkhaiActionPerformed

    private void cbo_chon_kichthuockhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_chon_kichthuockhoaActionPerformed
        // TODO add your handling code here:
        kich_thuoc_key = Integer.parseInt((String) cbo_chon_kichthuockhoa.getSelectedItem());
    }//GEN-LAST:event_cbo_chon_kichthuockhoaActionPerformed

    private void btn_chon_file_cankyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chon_file_cankyActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();

        // Bộ lọc file cho phép chọn các loại tệp cụ thể
        FileNameExtensionFilter filter = new FileNameExtensionFilter("pdf", "docx", "doc", "exe", "xls", "xlsx", "jpg", "png", "mp3", "mp4", "flv", "ico", "txt");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();

            // Lấy đương dẫn file và hiển thị lên txt_area_filecanky
            String attach = file.toString();
            txt_area_filecanky_CHON.setText(attach);
        }
    }//GEN-LAST:event_btn_chon_file_cankyActionPerformed

    private void btn_chon_file_privatekeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chon_file_privatekeyActionPerformed
        // TODO add your handling code here:
        // Tạo một đối tượng JFileChooser
        JFileChooser chooser = new JFileChooser();

        // Thiết lập bộ lọc file để chỉ cho phép chọn các loại file cụ thể
        FileNameExtensionFilter filter = new FileNameExtensionFilter("pdf", "docx", "doc", "txt");
        chooser.setFileFilter(filter);

        // Hiển thị hộp thoại chọn file và chờ người dùng chọn
        int returnVal = chooser.showOpenDialog(null);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            // Nếu người dùng chọn một file
            File file = chooser.getSelectedFile();

            // Đọc nội dung từ file và hiển thị lên txt_area_khoabimat_upfile
            try (Scanner scanner = new Scanner(file)) {
                StringBuilder content = new StringBuilder();
                while (scanner.hasNextLine()) {
                    content.append(scanner.nextLine()).append("\n");
                }
                // Hiển thị nội dung file lên txt_area_khoabimat_upfile
                txt_area_khoabimat_CHON.setText(content.toString());
            } catch (FileNotFoundException ex) {
                // Xử lý nếu có lỗi khi đọc file
                JOptionPane.showMessageDialog(null, "Không thể đọc file", "Lỗi", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btn_chon_file_privatekeyActionPerformed

//    // Phương thức thực hiện ký số theo cách 1
//    private void kySoCach1() {
//        String filename = txt_area_filecanky_CHON.getText().replace('\\', '/');
//        if (filename.isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Hãy chọn file cần ký!", "Thông báo", JOptionPane.ERROR_MESSAGE);
//            return;
//        }
//
//        SHA1 sha1 = new SHA1();
//        try {
//            // Tính toán giá trị băm của nội dung file và chuyển đổi nó thành một đối tượng BigInteger. .abs() được sử dụng để đảm bảo rằng giá trị là không âm.
//            BigInteger sh1 = new BigInteger(sha1.md(filename).abs().toString());
//            txt_area_SHA_KY.setText(sh1.toString());
//
//            // Mã hoá mã băm SHA bằng thuật toán RSA, sử dụng phương thức ma_hoa()
//            txt_area_chukyso_KY.setText(rsa.v1_mahoa(sh1).toString());
//            btn_luu_chukyso.setEnabled(true);
//            JOptionPane.showMessageDialog(null, "Tạo chữ ký số thành công!");
//        } catch (Exception ex) {
//            Logger.getLogger(v3_TaoKhoaVaKy.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }

    // Phương thức thực hiện ký số theo cách 2
    private void kySoCach2() {
        String filename = txt_area_filecanky_CHON.getText().replace('\\', '/');
        if (filename.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Hãy chọn file cần ký!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return;
        }

        SHA1 sha1 = new SHA1();
        try {
            BigInteger sh1 = new BigInteger(sha1.md(filename).abs().toString());
            txt_area_SHA_KY.setText(sh1.toString());

            // Lấy khoá bí mật từ txt_area_khoabimat_upfile
            BigInteger privateKey = new BigInteger(txt_area_khoabimat_CHON.getText().trim());

            // Ký số cho mã băm SHA bằng thuật toán RSA
            BigInteger digitalSignature = rsa.v1_mahoa(sh1, privateKey);

            String sign = String.format("%dF%d", digitalSignature, rsa.getModul());

            // Hiển thị chữ ký số lên txt_area_chukyso_duoctao
            txt_area_chukyso_KY.setText(sign);

            // Cho phép lưu chữ ký số
            btn_luu_chukyso.setEnabled(true);

            JOptionPane.showMessageDialog(null, "Tạo chữ ký số thành công!");
        } catch (Exception ex) {
            Logger.getLogger(v3_TaoKhoaVaKy.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void btn_kysoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kysoActionPerformed
        // TODO add your handling code here:
        // Kiểm tra xem txt_area_khoabimat_upfile có dữ liệu không
        String privateKeyContent = txt_area_khoabimat_CHON.getText().trim();
        if (!privateKeyContent.isEmpty()) {
            // CÁCH 2: Sử dụng khoá bí mật từ txt_area_khoabimat_upfile
            kySoCach2();
        } else {
            // CÁCH 1: Sử dụng mã băm SHA của file để ký số
            //kySoCach1();
        }
    }//GEN-LAST:event_btn_kysoActionPerformed

    private void btn_luu_chukysoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luu_chukysoActionPerformed
        // TODO add your handling code here:
        // Kiểm tra xem vùng văn bản chữ ký số có trống không
        if (txt_area_chukyso_KY.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Chữ ký số chưa được tạo. Hãy kiểm tra lại trước khi lưu.", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return; // Dừng hàm nếu chưa tạo chữ ký số
        }

        // Lấy chữ ký số từ vùng văn bản
        String chuKySo = txt_area_chukyso_KY.getText();

        // Mở hộp thoại chọn vị trí lưu file
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Chọn vị trí lưu file");

        // Bộ lọc cho phép chọn tệp có định dạng .txt
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Tệp văn bản (*.txt)", "txt");
        chooser.setFileFilter(filter);

        // Hiển thị hộp thoại lưu và lấy kết quả
        int userSelection = chooser.showSaveDialog(null);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            // Lấy đường dẫn đến file được chọn
            File fileToSave = chooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();

            // Kiểm tra nếu đường dẫn không có định dạng .txt, thêm phần mở rộng .txt
            if (!filePath.toLowerCase().endsWith(".txt")) {
                filePath += ".txt";
            }

            // Lưu chữ ký số vào file .txt
            try {
                java.nio.file.Files.write(java.nio.file.Paths.get(filePath), chuKySo.getBytes());
                JOptionPane.showMessageDialog(null, "Lưu chữ ký số thành công vào " + filePath);
            } catch (IOException ex) {
                Logger.getLogger(v3_TaoKhoaVaKy.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Lỗi khi lưu file", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_luu_chukysoActionPerformed

    private void btn_RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RESETActionPerformed
        // TODO add your handling code here:.
        // Đặt lại nội dung của tất cả các vùng văn bản về chuỗi trống
        txt_area_filecanky_CHON.setText("");
        txt_area_khoabimat_CHON.setText("");

        txt_area_khoabimat_DUOCTAO.setText("");
        txt_area_khoacongkhai_DUOCTAO.setText("");

        txt_area_SHA_KY.setText("");
        txt_area_chukyso_KY.setText("");
    }//GEN-LAST:event_btn_RESETActionPerformed

    private void btn_move_xacminhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_move_xacminhActionPerformed
        // TODO add your handling code here:
        v3_XacMinh v3_xm = new v3_XacMinh();
        v3_xm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_move_xacminhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v3_TaoKhoaVaKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v3_TaoKhoaVaKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v3_TaoKhoaVaKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v3_TaoKhoaVaKy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v3_TaoKhoaVaKy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_RESET;
    private javax.swing.JButton btn_chon_file_canky;
    private javax.swing.JButton btn_chon_file_privatekey;
    private javax.swing.JButton btn_kyso;
    private javax.swing.JButton btn_luu_chukyso;
    private javax.swing.JButton btn_luu_khoabimat;
    private javax.swing.JButton btn_luu_khoacongkhai;
    private java.awt.Button btn_move_xacminh;
    private javax.swing.JButton btn_quaylai;
    private javax.swing.JButton btn_taokhoa;
    private javax.swing.JComboBox<String> cbo_chon_kichthuockhoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea txt_area_SHA_KY;
    private javax.swing.JTextArea txt_area_chukyso_KY;
    private javax.swing.JTextArea txt_area_filecanky_CHON;
    private javax.swing.JTextArea txt_area_khoabimat_CHON;
    private javax.swing.JTextArea txt_area_khoabimat_DUOCTAO;
    private javax.swing.JTextArea txt_area_khoacongkhai_DUOCTAO;
    // End of variables declaration//GEN-END:variables
}
