/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author SONDAY
 */
import DAO.*;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;

import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.math.BigInteger;

public class v4_TaoKhoa extends javax.swing.JFrame {

    /**
     * Creates new form v4_TaoKhoa
     */
    static int kich_thuoc_key;
    static AlgorithmRSA rsa;

    public v4_TaoKhoa() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Tạo khoá ký số");

        this.txt_tenchucvu.setText(Login_GUI.chucvu_User);
        this.txt_tenchucvu.setHorizontalAlignment(SwingConstants.CENTER);
        this.txt_tenchucvu.setEditable(false);

        kich_thuoc_key = Integer.parseInt((String) cbo_chon_kichthuockhoa.getSelectedItem());
        rsa = new AlgorithmRSA();
        rsa.TaoKhoaRSA(kich_thuoc_key);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbo_chon_kichthuockhoa = new javax.swing.JComboBox<>();
        btn_luu_khoabimat = new javax.swing.JButton();
        btn_taokhoa = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_area_khoabimat_DUOCTAO = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btn_luu_khoacongkhai = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_area_khoacongkhai_DUOCTAO = new javax.swing.JTextArea();
        btn_quaylai = new javax.swing.JButton();
        txt_tenchucvu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("TẠO KHOÁ KÝ SỐ");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TẠO KHOÁ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Kích thước:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Khoá bí mật:");

        cbo_chon_kichthuockhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "256", "512", "1024", "2048", "3072" }));
        cbo_chon_kichthuockhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_chon_kichthuockhoaActionPerformed(evt);
            }
        });

        btn_luu_khoabimat.setBackground(new java.awt.Color(153, 255, 255));
        btn_luu_khoabimat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_luu_khoabimat.setText("Lưu khoá bí mật");
        btn_luu_khoabimat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luu_khoabimatActionPerformed(evt);
            }
        });

        btn_taokhoa.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btn_taokhoa.setText("TẠO KHOÁ");
        btn_taokhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taokhoaActionPerformed(evt);
            }
        });

        txt_area_khoabimat_DUOCTAO.setColumns(20);
        txt_area_khoabimat_DUOCTAO.setRows(5);
        jScrollPane3.setViewportView(txt_area_khoabimat_DUOCTAO);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Khoá công khai:");

        btn_luu_khoacongkhai.setBackground(new java.awt.Color(153, 255, 255));
        btn_luu_khoacongkhai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_luu_khoacongkhai.setText("Lưu khoá công khai");
        btn_luu_khoacongkhai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luu_khoacongkhaiActionPerformed(evt);
            }
        });

        txt_area_khoacongkhai_DUOCTAO.setColumns(20);
        txt_area_khoacongkhai_DUOCTAO.setRows(5);
        jScrollPane4.setViewportView(txt_area_khoacongkhai_DUOCTAO);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_taokhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_luu_khoacongkhai, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6)
                        .addGap(33, 33, 33)
                        .addComponent(cbo_chon_kichthuockhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(btn_luu_khoabimat, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_luu_khoabimat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbo_chon_kichthuockhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_luu_khoacongkhai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_taokhoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        btn_quaylai.setText("Trở về");
        btn_quaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quaylaiActionPerformed(evt);
            }
        });

        txt_tenchucvu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_tenchucvu.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_tenchucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(btn_quaylai))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(jLabel1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tenchucvu, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btn_quaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbo_chon_kichthuockhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_chon_kichthuockhoaActionPerformed
        // TODO add your handling code here:
        kich_thuoc_key = Integer.parseInt((String) cbo_chon_kichthuockhoa.getSelectedItem());
    }//GEN-LAST:event_cbo_chon_kichthuockhoaActionPerformed

    private void btn_luu_khoabimatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luu_khoabimatActionPerformed
        // TODO add your handling code here:
        // Kiểm tra xem vùng văn bản khóa bí mật có trống không
        if (txt_area_khoabimat_DUOCTAO.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Khóa bí mật chưa được tạo. Hãy tạo trước khi lưu.", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return; // Dừng hàm nếu chưa tạo khóa bí mật
        }

        // Lấy khóa bí mật từ vùng văn bản
        String khoaBiMat = txt_area_khoabimat_DUOCTAO.getText();

        // Mở hộp thoại chọn vị trí lưu file
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Chọn vị trí lưu file");

        // Bộ lọc cho phép chọn tệp có định dạng .txt
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Tệp văn bản (*.txt)", "txt");
        chooser.setFileFilter(filter);

        // Hiển thị hộp thoại lưu và lấy kết quả
        int userSelection = chooser.showSaveDialog(null);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            // Lấy đường dẫn đến file được chọn
            File fileToSave = chooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();

            // Kiểm tra nếu đường dẫn không có định dạng .txt, thêm phần mở rộng .txt
            if (!filePath.toLowerCase().endsWith(".txt")) {
                filePath += ".txt";
            }

            // Lưu khóa bí mật vào file .txt
            try {
                java.nio.file.Files.write(java.nio.file.Paths.get(filePath), khoaBiMat.getBytes());
                JOptionPane.showMessageDialog(null, "Lưu khóa bí mật thành công vào " + filePath);
            } catch (IOException ex) {
                Logger.getLogger(v4_TaoKhoa.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Lỗi khi lưu file", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_luu_khoabimatActionPerformed

    private void btn_taokhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taokhoaActionPerformed
        // TODO add your handling code here:
        rsa.TaoKhoaRSA(kich_thuoc_key);
        txt_area_khoabimat_DUOCTAO.setText(String.format("%sA%s", rsa.getKhoa_cong_khai().toString(), rsa.getModul()));
        txt_area_khoacongkhai_DUOCTAO.setText(rsa.getKhoa_bi_mat().toString());

        btn_luu_khoabimat.setEnabled(true);
        btn_luu_khoacongkhai.setEnabled(true);
    }//GEN-LAST:event_btn_taokhoaActionPerformed

    private void btn_luu_khoacongkhaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luu_khoacongkhaiActionPerformed
        // TODO add your handling code here:
        // Kiểm tra xem vùng văn bản khóa công khai có trống không
        if (txt_area_khoacongkhai_DUOCTAO.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Khóa công khai chưa được tạo. Hãy tạo trước khi lưu.", "Thông báo", JOptionPane.ERROR_MESSAGE);
            return; // Dừng hàm nếu chưa tạo khóa công khai
        }

        // Lấy khóa công khai từ vùng văn bản
        String khoaCongKhai = txt_area_khoacongkhai_DUOCTAO.getText();

        // Mở hộp thoại chọn vị trí lưu file
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Chọn vị trí lưu file");

        // Bộ lọc cho phép chọn tệp có định dạng .txt
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Tệp văn bản (*.txt)", "txt");
        chooser.setFileFilter(filter);

        // Hiển thị hộp thoại lưu và lấy kết quả
        int userSelection = chooser.showSaveDialog(null);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            // Lấy đường dẫn đến file được chọn
            File fileToSave = chooser.getSelectedFile();
            String filePath = fileToSave.getAbsolutePath();

            // Kiểm tra nếu đường dẫn không có định dạng .txt, thêm phần mở rộng .txt
            if (!filePath.toLowerCase().endsWith(".txt")) {
                filePath += ".txt";
            }

            // Lưu khóa công khai vào file .txt
            try {
                java.nio.file.Files.write(java.nio.file.Paths.get(filePath), khoaCongKhai.getBytes());
                JOptionPane.showMessageDialog(null, "Lưu khóa công khai thành công vào " + filePath);
            } catch (IOException ex) {
                Logger.getLogger(v4_TaoKhoa.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Lỗi khi lưu file", "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_luu_khoacongkhaiActionPerformed

    private void btn_quaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quaylaiActionPerformed
        // TODO add your handling code here:
        Managanent_GUI qlc = new Managanent_GUI();
        qlc.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_quaylaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v4_TaoKhoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v4_TaoKhoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v4_TaoKhoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v4_TaoKhoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v4_TaoKhoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_luu_khoabimat;
    private javax.swing.JButton btn_luu_khoacongkhai;
    private javax.swing.JButton btn_quaylai;
    private javax.swing.JButton btn_taokhoa;
    private javax.swing.JComboBox<String> cbo_chon_kichthuockhoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea txt_area_khoabimat_DUOCTAO;
    private javax.swing.JTextArea txt_area_khoacongkhai_DUOCTAO;
    private javax.swing.JTextField txt_tenchucvu;
    // End of variables declaration//GEN-END:variables
}
